# Generated by Django 2.2.4 on 2019-09-03 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencijeprijema',
            name='sifra_artikla',
            field=models.ForeignKey(db_column='sifra_artikla', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ep_artikli_sif_art', serialize=False, to='approda.Artikli'),
        ),
        migrations.AlterField(
            model_name='evidencijeprijema',
            name='sifra_dobavljaca',
            field=models.ForeignKey(db_column='sifra_dobavljaca', on_delete=django.db.models.deletion.CASCADE, related_name='ep_otpremnice_sif_dob', to='approda.Otpremnice'),
        ),
        migrations.AlterField(
            model_name='evidencijeprijema',
            name='sifra_otpremnice',
            field=models.ForeignKey(db_column='sifra_otpremnice', on_delete=django.db.models.deletion.CASCADE, related_name='ep_otpremnice_sif_otp', to='approda.Otpremnice'),
        ),
    ]
