# Generated by Django 2.2.5 on 2020-10-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dobavljaci',
            name='sifra_dobavljaca',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='objekti',
            name='pib',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
