# Generated by Django 2.2.5 on 2020-10-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approda', '0002_auto_20201005_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racuni',
            name='ukupno',
            field=models.BigIntegerField(null=True),
        ),
    ]
