# Generated by Django 2.2.5 on 2020-10-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approda', '0003_auto_20201005_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencijeprijema',
            name='naziv_objekta',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
