# Generated by Django 2.2.4 on 2019-09-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approda', '0003_auto_20190904_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikli',
            name='sifra_artikla',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
