# Generated by Django 2.2.4 on 2019-09-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approda', '0004_auto_20190904_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikli',
            name='sifra_artikla',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evidencijeprijema',
            name='sifra_artikla',
            field=models.ForeignKey(db_column='sifra_artikla', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='approda.Artikli'),
        ),
    ]
