# Generated by Django 2.2.5 on 2019-09-05 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('approda', '0005_auto_20190904_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencijeprijema',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stavkeracuna',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evidencijeprijema',
            name='sifra_artikla',
            field=models.ForeignKey(db_column='sifra_artikla', on_delete=django.db.models.deletion.CASCADE, to='approda.Artikli'),
        ),
        migrations.AlterField(
            model_name='stavkeracuna',
            name='sifra_artikla',
            field=models.ForeignKey(db_column='sifra_artikla', on_delete=django.db.models.deletion.CASCADE, to='approda.Artikli'),
        ),
    ]
