# Generated by Django 2.2.5 on 2019-09-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('approda', '0007_auto_20190905_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencijeprijema',
            name='pk_evidencije_prijema',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evidencijeprijema',
            name='sifra_otpremnice',
            field=models.ForeignKey(db_column='sifra_otpremnice', on_delete=django.db.models.deletion.CASCADE, to='approda.Otpremnice'),
        ),
        migrations.AlterField(
            model_name='stavkeracuna',
            name='pk_stavke_racuna',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
